#!/bin/bash

# MAINTAINER Johan Maurel

name="naoserver"
container="nao"
port="80"

function help {
    echo "     -h, --help : Print help"
    echo "     -i, --install : To install nao server. Beware the install kill your working instance"
    echo "     --start : To start nao server"
    echo "     --stop : To stop nao server"
    echo "     -c, --compile : To generate the app.js"
}

function install {

    echo "Do you want to construct the image by your own: y or n ?"
    read answer

    while [[ $answer != "y" && $answer != "n" ]]
    do
        if [ $answer == "q" ]; then
            exit 0
        fi
        echo "you have entered an invalid response. Please try again"
        echo "Do you want to construct the image by your own : y or n ?"
        read answer
    done

    echo "You are installing on the raspberry pi: y or n ?"
    read answer1

    while [[ $answer1 != "y" && $answer1 != "n" ]]
    do
        if [ $answer1 == "q" ]; then
            exit 0
        fi
        echo "you have entered an invalid response. Please try again"
        echo "You are installing on the raspberry pi: y or n ?"
        read answer1
    done

    docker stop $container
    docker container prune -f

    if [ -z $(docker volume list | grep $name) ]; then
        docker volume create naobox # Mariadb volume for data persistance
    fi

    if [ $answer == "y" ]; then
        if [ $answer1 == "y" ]; then
            docker build -t $name build/rpi
        else
            docker build -t $name build/
        fi
    else
        if [ $answer1 == "y" ]; then
            docker pull cactusmamelut/rpi-naoboxv2-iiil
            docker tag cactusmamelut/rpi-naoboxv2-iiil naoserver
        else
            docker pull cactusmamelut/naoboxv2-iiil
            docker tag cactusmamelut/naoboxv2-iiil naoserver
        fi
    fi
    start
    docker system prune -f
}

function start {
    if [ $(docker images | grep $name | wc -c) -gt "0" ]; then
        docker container prune -f
        if [ $(docker container ps | grep $container | wc -c) -eq "0" ]; then
            echo "You are installing on the raspberry pi: y or n ?"
            read answer1

            while [[ $answer1 != "y" && $answer1 != "n" ]]
            do
                if [ $answer1 == "q" ]; then
                    exit 0
                fi
                echo "you have entered an invalid response. Please try again"
                echo "You are installing on the raspberry pi: y or n ?"
                read answer1
            done

            if [ $answer1 == "y" ]; then
                docker run -d --name $container --restart=always -p80:80 -v$(pwd):/var/www/project $name
            else
                docker run -d --name $container -p80:80 -v$(pwd):/var/www/project $name
            fi
            
        else
            docker start nao
        fi
    else
        echo "You need to install by taping naoserver --install"
    fi
}

function stop {
    docker stop nao
}

function compile {
    docker exec $container bash -c './build.sh'
}


if [ -n $(ls /usr/bin/ | grep "^docker$") ]; then

    if [ $(groups | grep docker | wc -c) -gt "0" ]; then

        if [ $1 == "-h" ] || [ $1 == "--help" ]; then
            help
            exit 0

        elif [ $1 == "-i" ] || [ $1 == "--install" ]; then
            install

        elif [ $1 == "--start" ]; then
            start

        elif [ $1 == "--stop" ]; then
            stop

        elif [ $1 == "-c" ] || [ $1 == "--compile" ]; then
            compile
        else
            echo "Need a valid argument"
            help
            exit 1
        fi

    else
        echo "Need execution permission on docker"
        exit 1
    fi
else
    echo "Install docker"
    exit 1
fi